version: '3.3'
services: 
  mysql:
    image: mysql:8.0.27
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --default-authentication-plugin=mysql_native_password
    ports: 
      - "3306:3306"
    volumes:
      - db-store:/var/lib/mysql
    environment: 
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: sound_share_app
    command: /bin/sh -c 'rm -rf tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0'
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: mysql
      RAILS_ENV: development
    depends_on:
      - mysql
    tty: true
    stdin_open: true

volumes:
  db-store: